# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* tsconfig.json ./
COPY src ./src

RUN npm install --ignore-scripts && npm run build

# Ensure executable permissions
RUN chmod +x build/index.js

# Use non-root user for security (optional)
# RUN addgroup -S appgroup && adduser -S appuser -G appgroup
# USER appuser

ENTRYPOINT ["node", "build/index.js"]
